# Generated by Django 4.2.27 on 2025-12-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="物料编号"
                    ),
                ),
                (
                    "material_name",
                    models.CharField(max_length=100, verbose_name="物料名称"),
                ),
                (
                    "max_stock",
                    models.IntegerField(default=0, verbose_name="最大库存量"),
                ),
                (
                    "min_stock",
                    models.IntegerField(default=0, verbose_name="最小库存量"),
                ),
                (
                    "current_stock",
                    models.IntegerField(default=0, verbose_name="当前库存量"),
                ),
                (
                    "stock_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="库存价值",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "库存",
                "verbose_name_plural": "库存",
                "db_table": "stock",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(max_length=50, verbose_name="物料编号"),
                ),
                (
                    "material_name",
                    models.CharField(max_length=100, verbose_name="物料名称"),
                ),
                ("out_time", models.DateTimeField(verbose_name="出库时间")),
                ("out_quantity", models.IntegerField(verbose_name="出库数量")),
                (
                    "out_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="出库价值"
                    ),
                ),
                (
                    "out_type",
                    models.CharField(
                        choices=[
                            ("production", "生产领料"),
                            ("sales", "销售提货"),
                            ("other", "其他出库"),
                        ],
                        max_length=20,
                        verbose_name="出库类型",
                    ),
                ),
                (
                    "operator",
                    models.CharField(blank=True, max_length=50, verbose_name="操作人"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.stock",
                        verbose_name="关联库存",
                    ),
                ),
            ],
            options={
                "verbose_name": "出库记录",
                "verbose_name_plural": "出库记录",
                "db_table": "stock_out",
                "ordering": ["-out_time"],
            },
        ),
        migrations.CreateModel(
            name="StockIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(max_length=50, verbose_name="物料编号"),
                ),
                (
                    "material_name",
                    models.CharField(max_length=100, verbose_name="物料名称"),
                ),
                ("in_time", models.DateTimeField(verbose_name="入库时间")),
                ("in_quantity", models.IntegerField(verbose_name="入库数量")),
                (
                    "in_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="入库价值"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.stock",
                        verbose_name="关联库存",
                    ),
                ),
            ],
            options={
                "verbose_name": "入库记录",
                "verbose_name_plural": "入库记录",
                "db_table": "stock_in",
                "ordering": ["-in_time"],
            },
        ),
    ]
