# Generated by Django 4.2.27 on 2025-12-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='in_type',
            field=models.CharField(choices=[('purchase', '采购入库'), ('production', '生产入库'), ('return', '退货入库'), ('other', '其他入库')], default='purchase', max_length=20, verbose_name='入库类型'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
    ]
