# Generated by Django 4.2.27 on 2025-12-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_stockin_in_type_stockin_operator_stockin_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="category",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="类别"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="spec",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="规格型号"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="status",
            field=models.CharField(
                choices=[("active", "启用"), ("inactive", "停用")],
                default="active",
                max_length=10,
                verbose_name="状态",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="supplier",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="供应商"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="unit",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="单位"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="单价"
            ),
        ),
        migrations.AddField(
            model_name="stockin",
            name="bill_no",
            field=models.CharField(
                default="", max_length=30, unique=True, verbose_name="单据号"
            ),
        ),
        migrations.AddField(
            model_name="stockin",
            name="supplier",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="供应商"
            ),
        ),
        migrations.AddField(
            model_name="stockout",
            name="bill_no",
            field=models.CharField(
                default="", max_length=30, unique=True, verbose_name="单据号"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_value",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="库存价值"
            ),
        ),
        migrations.AlterField(
            model_name="stockin",
            name="in_type",
            field=models.CharField(
                choices=[
                    ("purchase", "采购入库"),
                    ("production", "生产入库"),
                    ("return", "退货入库"),
                    ("other", "其他入库"),
                    ("adjust_gain", "盘点盘盈"),
                ],
                default="purchase",
                max_length=20,
                verbose_name="入库类型",
            ),
        ),
        migrations.AlterField(
            model_name="stockin",
            name="in_value",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="入库价值"
            ),
        ),
        migrations.AlterField(
            model_name="stockout",
            name="operator",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="操作人"
            ),
        ),
        migrations.AlterField(
            model_name="stockout",
            name="out_type",
            field=models.CharField(
                choices=[
                    ("production", "生产领料"),
                    ("sales", "销售提货"),
                    ("other", "其他出库"),
                    ("adjust_loss", "盘点盘亏"),
                ],
                max_length=20,
                verbose_name="出库类型",
            ),
        ),
        migrations.AlterField(
            model_name="stockout",
            name="out_value",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="出库价值"
            ),
        ),
        migrations.AlterField(
            model_name="stockout",
            name="remark",
            field=models.TextField(blank=True, default="", verbose_name="备注"),
        ),
    ]
