# Generated by Django 4.2.27 on 2025-12-21 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_stock_category_stock_spec_stock_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(max_length=50, verbose_name="物料编号"),
                ),
                (
                    "material_name",
                    models.CharField(max_length=100, verbose_name="物料名称"),
                ),
                (
                    "warning_type",
                    models.CharField(
                        choices=[("low", "库存不足"), ("high", "库存过高")],
                        max_length=10,
                        verbose_name="预警类型",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("warning", "警告"), ("danger", "危险")],
                        default="warning",
                        max_length=10,
                        verbose_name="预警级别",
                    ),
                ),
                ("current_stock", models.IntegerField(verbose_name="当前库存")),
                ("min_stock", models.IntegerField(default=0, verbose_name="最小库存")),
                ("max_stock", models.IntegerField(default=0, verbose_name="最大库存")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("handled", "已处理"),
                            ("ignored", "已忽略"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "handled_by",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="处理人"
                    ),
                ),
                (
                    "handled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.stock",
                        verbose_name="关联库存",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存预警",
                "verbose_name_plural": "库存预警",
                "db_table": "stock_warning",
                "ordering": ["-created_at"],
            },
        ),
    ]
