# Generated by Django 4.2.27 on 2025-12-21 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_stockwarning"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCountTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_no",
                    models.CharField(max_length=30, unique=True, verbose_name="任务号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待盘点"),
                            ("doing", "盘点中"),
                            ("done", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                ("created_by", models.CharField(max_length=50, verbose_name="创建人")),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "盘点任务",
                "verbose_name_plural": "盘点任务",
                "db_table": "stock_count_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockCountItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_code",
                    models.CharField(max_length=50, verbose_name="物料编号"),
                ),
                (
                    "material_name",
                    models.CharField(max_length=100, verbose_name="物料名称"),
                ),
                ("book_qty", models.IntegerField(verbose_name="账面数量")),
                (
                    "real_qty",
                    models.IntegerField(blank=True, null=True, verbose_name="实盘数量"),
                ),
                ("diff_qty", models.IntegerField(default=0, verbose_name="差异数量")),
                (
                    "diff_type",
                    models.CharField(
                        choices=[
                            ("gain", "盘盈"),
                            ("loss", "盘亏"),
                            ("none", "无差异"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="差异类型",
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "operator",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="操作人"
                    ),
                ),
                (
                    "operated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="操作时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.stock",
                        verbose_name="关联库存",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="stock.stockcounttask",
                        verbose_name="盘点任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "盘点明细",
                "verbose_name_plural": "盘点明细",
                "db_table": "stock_count_item",
                "ordering": ["id"],
            },
        ),
    ]
